server:
  port: 8002
spring:
  application:
    name: storageService
  cloud:
    alibaba:
      seata:
        tx-service-group: groupA
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: 0408
    driver-class-name: com.mysql.jdbc.Driver
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
