server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 0408
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  cloud:
    consul:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*.xml



