server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 0408
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false

mybatis:
  type-aliases-package: com.ltl.cloud-provider-payment-8001.entities
  mapper-locations: classpath:mapper/*.xml
