server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
#      web-context-unify: false
      transport:
        dashboard: localhost:8080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"
