server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 0408
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

mybatis:
  type-aliases-package: com.ltl.cloud-provider-payment-8001.entities
  mapper-locations: classpath:mapper/*.xml



