server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
